apiVersion: apps/v1
kind: Deployment
metadata:
  name: <% .Name %>
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: <% .Name %>
  template:
    spec:
      containers:
        - name: <% .Name %>
          image: fake-image
          resources:
            requests:
              memory: 128Mi
              cpu: 0.1
            limits:
              memory: 256Mi
              cpu: 0.5
          ports:
            - containerPort: <% index .Params `containerPort` %>
              name: http
          envFrom:
          - configMapRef:
              name: <% .Name %>-config
          # Uncomment the secretRef block below if your Playground application has secrets
          # See the README for instructions on how to create secrets
          #- secretRef:
          #    name: <% .Name %>-secrets
          readinessProbe:
            httpGet:
              port: http
              path: /
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
